/* Art & Gifts — natural FR/IT/DE page copy. Loaded after multilingual.js. */
(() => {
  'use strict';
  const maps = {
    fr: {
      'Custom Creations':'Créations sur mesure','Visit Body Glow':'Découvrir Body Glow',
      'A little clarity before we begin':'Quelques repères avant de commencer','Frequently Asked Questions':'Questions fréquentes','Everything you need to know about handmade orders, customization, photographs, production and payment.':'Tout ce qu’il faut savoir sur les commandes artisanales, la personnalisation, les photos de référence, la fabrication et le paiement.',
      'Is every piece handmade?':'Chaque pièce est-elle réalisée à la main ?','Yes. Velvet Charms Art & Gifts is built around handmade and small-batch work rather than mass production. Production begins according to the confirmed production slot for your order.':'Oui. Velvet Charms Art & Gifts repose sur le travail artisanal et les petites séries, jamais sur la production de masse. La fabrication commence selon le créneau de production confirmé pour votre commande.',
      'When does the making time begin?':'Quand commence le délai de fabrication ?','The approximate making time shown for a product begins from the production start date confirmed by us, not automatically from the payment date. Payment reserves your place in the queue.':'Le délai de fabrication indicatif affiché pour un produit commence à la date de mise en production que nous vous confirmons, et non automatiquement au jour du paiement. Le paiement réserve votre place dans la file de production.',
      'Can I request a special date?':'Puis-je demander une date particulière ?','Yes. Use the optional preferred-date field in the cart. We will review the current production schedule and confirm whether the requested date is realistic.':'Oui. Indiquez-la dans le champ facultatif prévu dans le panier. Nous vérifions notre planning de production et vous confirmons si la date souhaitée est réaliste.',
      'Can every catalogue product be customized?':'Tous les produits du catalogue peuvent-ils être personnalisés ?','Every product keeps a Request customization option. Depending on the category, you may choose style, palette, material, finish, gift presentation and other relevant options, and you can also leave special instructions.':'Chaque produit conserve une option de personnalisation. Selon la catégorie, vous pouvez choisir le style, la palette, le matériau, la finition, la présentation cadeau et d’autres détails pertinents, tout en ajoutant vos indications particulières.',
      'Can I send reference photographs?':'Puis-je envoyer des photos de référence ?','Yes. Customization supports private reference photographs for products where a visual reference is useful. They are intended only for understanding and creating your request.':'Oui. Lorsque cela est utile, la personnalisation permet d’ajouter des photos de référence privées. Elles servent uniquement à comprendre votre demande et à réaliser votre création.',
      'Can you create something not listed in the catalogue?':'Pouvez-vous créer quelque chose qui ne figure pas dans le catalogue ?','Yes. Use Custom Creations or Contact to describe the idea. Completely new commissions receive an individual feasibility check, price and production estimate before work begins.':'Oui. Utilisez Créations sur mesure ou Contact pour nous décrire votre idée. Toute demande entièrement nouvelle fait l’objet d’une étude de faisabilité, d’un prix et d’un délai de fabrication individualisés avant le début du travail.',
      'How do payments work?':'Comment fonctionne le paiement ?','Catalogue orders are processed securely through PayPal. You may use PayPal or, where available, an eligible debit or credit card. The server verifies catalogue prices before payment.':'Les commandes du catalogue sont réglées en toute sécurité via PayPal. Vous pouvez utiliser PayPal ou, lorsque l’option est disponible, une carte de débit ou de crédit éligible. Le serveur vérifie les prix du catalogue avant le paiement.',
      'Are Romanian prices different?':'Les prix affichés en Roumanie sont-ils différents ?','Yes. When the site is accessed from Romania, a dedicated RON price grid is used instead of a simple conversion of international prices. Access from other countries keeps the international catalogue pricing, displayed in the visitor\'s applicable local currency where supported.':'Oui. Lorsque le site est consulté depuis la Roumanie, une grille tarifaire dédiée en RON s’applique au lieu d’une simple conversion des prix internationaux. Depuis les autres pays, les tarifs internationaux du catalogue sont conservés et affichés dans la devise locale du visiteur lorsque cette conversion est prise en charge.',
      'How is shipping calculated?':'Comment les frais de livraison sont-ils calculés ?','Shipping is handled separately because paintings, leather bags, clocks and small accessories have very different sizes and weights. The appropriate cost is confirmed according to destination and parcel details.':'La livraison est calculée séparément, car un tableau, un sac en cuir, une horloge et un petit accessoire n’ont ni le même format ni le même poids. Le coût adapté est confirmé selon la destination et les caractéristiques du colis.',
      'What are the Velvet Passport and charms?':'Que sont le Velvet Passport et les charms ?','They are part of the collectible Velvet experience. Selected orders can include a Passport choice, collectible charm, card and premium wrapping so purchases can become part of a continuing collection.':'Ils font partie de l’expérience Velvet à collectionner. Certaines commandes peuvent inclure un choix de Passport, un charm à collectionner, une carte et un emballage premium, afin que chaque achat puisse devenir un nouveau chapitre de votre collection.',
      'Fourteen artists, one creative home':'Quatorze artistes, un même atelier créatif','About Velvet Charms':'À propos de Velvet Charms','Our studio is shaped by fourteen individual perspectives and a shared commitment to thoughtful, high-quality work.':'Notre atelier réunit quatorze sensibilités différentes autour d’un même engagement : créer avec soin, exigence et attention aux détails.','Made by hand, made to matter':'Fait main, pensé pour compter','Every piece begins with materials, skill and a story. We work across painting, sculpture, resin, leather, textiles and mixed media to create objects that feel personal rather than mass-produced.':'Chaque pièce naît de matériaux, d’un savoir-faire et d’une histoire. Nous travaillons la peinture, la sculpture, la résine, le cuir, le textile et les techniques mixtes pour créer des objets personnels, loin de la production standardisée.','Created around your story':'Créé autour de votre histoire','Many creations can be shaped around a photograph, a memory, a person, a pet, a place or an idea. We guide the details before production begins so the finished piece feels genuinely yours.':'De nombreuses créations peuvent naître d’une photo, d’un souvenir, d’une personne, d’un animal, d’un lieu ou simplement d’une idée. Nous définissons les détails avec vous avant la fabrication afin que la pièce finale vous ressemble vraiment.','Beyond the catalogue':'Au-delà du catalogue','Have Something Different in Mind?':'Vous imaginez autre chose ?','If the creation you are looking for is not currently displayed, send us your idea. When it fits the skills of our collective, we assess the materials, complexity, price and production timeframe individually before any work begins.':'Si la création que vous recherchez n’apparaît pas dans le catalogue, envoyez-nous votre idée. Lorsqu’elle correspond aux savoir-faire de notre collectif, nous évaluons individuellement les matériaux, la complexité, le prix et le délai de fabrication avant tout début de travail.','Share your idea':'Partager votre idée'
    },
    it: {
      'Custom Creations':'Creazioni su misura','Visit Body Glow':'Scopri Body Glow',
      'A little clarity before we begin':'Qualche risposta prima di iniziare','Frequently Asked Questions':'Domande frequenti','Everything you need to know about handmade orders, customization, photographs, production and payment.':'Tutto ciò che serve sapere su ordini artigianali, personalizzazione, fotografie di riferimento, produzione e pagamento.',
      'Is every piece handmade?':'Ogni pezzo è realizzato a mano?','Yes. Velvet Charms Art & Gifts is built around handmade and small-batch work rather than mass production. Production begins according to the confirmed production slot for your order.':'Sì. Velvet Charms Art & Gifts nasce dal lavoro artigianale e dalle piccole serie, non dalla produzione di massa. La lavorazione inizia in base allo slot di produzione confermato per il tuo ordine.',
      'When does the making time begin?':'Quando inizia il tempo di realizzazione?','The approximate making time shown for a product begins from the production start date confirmed by us, not automatically from the payment date. Payment reserves your place in the queue.':'Il tempo di realizzazione indicativo mostrato per un prodotto decorre dalla data di inizio produzione che ti confermiamo, non automaticamente dal giorno del pagamento. Il pagamento riserva il tuo posto nella coda di produzione.',
      'Can I request a special date?':'Posso richiedere una data particolare?','Yes. Use the optional preferred-date field in the cart. We will review the current production schedule and confirm whether the requested date is realistic.':'Sì. Usa il campo facoltativo per la data preferita nel carrello. Controlleremo il programma di produzione e ti confermeremo se la data richiesta è realisticamente possibile.',
      'Can every catalogue product be customized?':'Tutti i prodotti del catalogo possono essere personalizzati?','Every product keeps a Request customization option. Depending on the category, you may choose style, palette, material, finish, gift presentation and other relevant options, and you can also leave special instructions.':'Ogni prodotto mantiene l’opzione di personalizzazione. A seconda della categoria puoi scegliere stile, palette, materiale, finitura, confezione regalo e altri dettagli pertinenti, oltre ad aggiungere indicazioni speciali.',
      'Can I send reference photographs?':'Posso inviare fotografie di riferimento?','Yes. Customization supports private reference photographs for products where a visual reference is useful. They are intended only for understanding and creating your request.':'Sì. Quando è utile, la personalizzazione permette di caricare fotografie di riferimento private. Vengono utilizzate esclusivamente per comprendere e realizzare la tua richiesta.',
      'Can you create something not listed in the catalogue?':'Potete creare qualcosa che non è presente nel catalogo?','Yes. Use Custom Creations or Contact to describe the idea. Completely new commissions receive an individual feasibility check, price and production estimate before work begins.':'Sì. Usa Creazioni su misura o Contatti per raccontarci l’idea. Le commissioni completamente nuove ricevono una valutazione individuale di fattibilità, prezzo e tempi di produzione prima dell’inizio del lavoro.',
      'How do payments work?':'Come funziona il pagamento?','Catalogue orders are processed securely through PayPal. You may use PayPal or, where available, an eligible debit or credit card. The server verifies catalogue prices before payment.':'Gli ordini del catalogo vengono elaborati in sicurezza tramite PayPal. Puoi utilizzare PayPal oppure, dove disponibile, una carta di debito o credito idonea. Il server verifica i prezzi del catalogo prima del pagamento.',
      'Are Romanian prices different?':'I prezzi visualizzati dalla Romania sono diversi?','Yes. When the site is accessed from Romania, a dedicated RON price grid is used instead of a simple conversion of international prices. Access from other countries keeps the international catalogue pricing, displayed in the visitor\'s applicable local currency where supported.':'Sì. Quando il sito viene visitato dalla Romania si applica una griglia prezzi dedicata in RON, invece di una semplice conversione dei prezzi internazionali. Da altri Paesi restano validi i prezzi internazionali del catalogo, mostrati nella valuta locale del visitatore dove la conversione è supportata.',
      'How is shipping calculated?':'Come viene calcolata la spedizione?','Shipping is handled separately because paintings, leather bags, clocks and small accessories have very different sizes and weights. The appropriate cost is confirmed according to destination and parcel details.':'La spedizione viene calcolata separatamente perché quadri, borse in pelle, orologi e piccoli accessori hanno dimensioni e pesi molto diversi. Il costo corretto viene confermato in base alla destinazione e alle caratteristiche del pacco.',
      'What are the Velvet Passport and charms?':'Cosa sono il Velvet Passport e i charm?','They are part of the collectible Velvet experience. Selected orders can include a Passport choice, collectible charm, card and premium wrapping so purchases can become part of a continuing collection.':'Fanno parte dell’esperienza Velvet da collezionare. Alcuni ordini possono includere una scelta Passport, un charm da collezione, un biglietto e una confezione premium, così ogni acquisto può diventare un nuovo capitolo della tua collezione.',
      'Fourteen artists, one creative home':'Quattordici artisti, un unico spazio creativo','About Velvet Charms':'Chi è Velvet Charms','Our studio is shaped by fourteen individual perspectives and a shared commitment to thoughtful, high-quality work.':'Il nostro atelier nasce da quattordici sensibilità diverse e da un impegno condiviso per un lavoro curato, autentico e di qualità.','Made by hand, made to matter':'Fatto a mano, creato per avere significato','Every piece begins with materials, skill and a story. We work across painting, sculpture, resin, leather, textiles and mixed media to create objects that feel personal rather than mass-produced.':'Ogni pezzo nasce da materiali, abilità e una storia. Lavoriamo con pittura, scultura, resina, pelle, tessili e tecniche miste per creare oggetti personali, lontani dalla produzione in serie.','Created around your story':'Creato intorno alla tua storia','Many creations can be shaped around a photograph, a memory, a person, a pet, a place or an idea. We guide the details before production begins so the finished piece feels genuinely yours.':'Molte creazioni possono nascere da una fotografia, un ricordo, una persona, un animale, un luogo o un’idea. Definiamo con te i dettagli prima della produzione, perché il pezzo finito possa sentirsi davvero tuo.','Beyond the catalogue':'Oltre il catalogo','Have Something Different in Mind?':'Hai in mente qualcosa di diverso?','If the creation you are looking for is not currently displayed, send us your idea. When it fits the skills of our collective, we assess the materials, complexity, price and production timeframe individually before any work begins.':'Se la creazione che cerchi non è presente nel catalogo, raccontaci la tua idea. Quando rientra nelle competenze del nostro collettivo, valutiamo individualmente materiali, complessità, prezzo e tempi di produzione prima di iniziare qualsiasi lavoro.','Share your idea':'Raccontaci la tua idea'
    },
    de: {
      'Custom Creations':'Individuelle Kreationen','Visit Body Glow':'Body Glow entdecken',
      'A little clarity before we begin':'Ein paar Antworten vorab','Frequently Asked Questions':'Häufige Fragen','Everything you need to know about handmade orders, customization, photographs, production and payment.':'Alles Wissenswerte zu handgefertigten Bestellungen, Personalisierung, Referenzfotos, Fertigung und Bezahlung.',
      'Is every piece handmade?':'Wird jedes Stück von Hand gefertigt?','Yes. Velvet Charms Art & Gifts is built around handmade and small-batch work rather than mass production. Production begins according to the confirmed production slot for your order.':'Ja. Velvet Charms Art & Gifts steht für Handarbeit und kleine Serien statt Massenproduktion. Die Fertigung beginnt entsprechend dem für Ihre Bestellung bestätigten Produktionszeitraum.',
      'When does the making time begin?':'Wann beginnt die Fertigungszeit?','The approximate making time shown for a product begins from the production start date confirmed by us, not automatically from the payment date. Payment reserves your place in the queue.':'Die angegebene ungefähre Fertigungszeit beginnt mit dem von uns bestätigten Produktionsstart und nicht automatisch am Zahlungstag. Mit der Zahlung reservieren Sie Ihren Platz in der Produktionsreihenfolge.',
      'Can I request a special date?':'Kann ich einen besonderen Wunschtermin angeben?','Yes. Use the optional preferred-date field in the cart. We will review the current production schedule and confirm whether the requested date is realistic.':'Ja. Nutzen Sie dazu das optionale Feld für den Wunschtermin im Warenkorb. Wir prüfen die aktuelle Produktionsplanung und bestätigen Ihnen, ob der gewünschte Termin realistisch ist.',
      'Can every catalogue product be customized?':'Kann jedes Katalogprodukt personalisiert werden?','Every product keeps a Request customization option. Depending on the category, you may choose style, palette, material, finish, gift presentation and other relevant options, and you can also leave special instructions.':'Bei jedem Produkt bleibt die Personalisierungsoption erhalten. Je nach Kategorie können Sie Stil, Farbwelt, Material, Finish, Geschenkpräsentation und weitere passende Details auswählen sowie besondere Hinweise hinterlassen.',
      'Can I send reference photographs?':'Kann ich Referenzfotos senden?','Yes. Customization supports private reference photographs for products where a visual reference is useful. They are intended only for understanding and creating your request.':'Ja. Bei Produkten, für die eine visuelle Vorlage hilfreich ist, können private Referenzfotos hochgeladen werden. Sie dienen ausschließlich dazu, Ihre Wünsche zu verstehen und Ihre Kreation anzufertigen.',
      'Can you create something not listed in the catalogue?':'Können Sie auch etwas anfertigen, das nicht im Katalog steht?','Yes. Use Custom Creations or Contact to describe the idea. Completely new commissions receive an individual feasibility check, price and production estimate before work begins.':'Ja. Beschreiben Sie Ihre Idee über Individuelle Kreationen oder Kontakt. Für vollständig neue Aufträge prüfen wir Machbarkeit, Preis und Fertigungszeit individuell, bevor die Arbeit beginnt.',
      'How do payments work?':'Wie funktioniert die Bezahlung?','Catalogue orders are processed securely through PayPal. You may use PayPal or, where available, an eligible debit or credit card. The server verifies catalogue prices before payment.':'Katalogbestellungen werden sicher über PayPal abgewickelt. Sie können PayPal oder – sofern verfügbar – eine geeignete Debit- oder Kreditkarte nutzen. Der Server prüft die Katalogpreise vor der Zahlung.',
      'Are Romanian prices different?':'Gibt es für Zugriffe aus Rumänien andere Preise?','Yes. When the site is accessed from Romania, a dedicated RON price grid is used instead of a simple conversion of international prices. Access from other countries keeps the international catalogue pricing, displayed in the visitor\'s applicable local currency where supported.':'Ja. Wird die Website aus Rumänien aufgerufen, gilt eine eigene Preisstaffel in RON statt einer einfachen Umrechnung der internationalen Preise. Bei Zugriff aus anderen Ländern bleiben die internationalen Katalogpreise bestehen und werden – soweit unterstützt – in der jeweils passenden lokalen Währung angezeigt.',
      'How is shipping calculated?':'Wie werden die Versandkosten berechnet?','Shipping is handled separately because paintings, leather bags, clocks and small accessories have very different sizes and weights. The appropriate cost is confirmed according to destination and parcel details.':'Der Versand wird separat berechnet, da Gemälde, Ledertaschen, Uhren und kleine Accessoires sehr unterschiedliche Größen und Gewichte haben. Die passenden Kosten bestätigen wir anhand von Zielort und Paketdetails.',
      'What are the Velvet Passport and charms?':'Was sind der Velvet Passport und die Charms?','They are part of the collectible Velvet experience. Selected orders can include a Passport choice, collectible charm, card and premium wrapping so purchases can become part of a continuing collection.':'Sie gehören zum sammelbaren Velvet Erlebnis. Ausgewählte Bestellungen können eine Passport-Option, einen sammelbaren Charm, eine Karte und eine hochwertige Verpackung enthalten, sodass Ihre Einkäufe Teil einer fortlaufenden Sammlung werden können.',
      'Fourteen artists, one creative home':'Vierzehn Künstler, ein kreatives Zuhause','About Velvet Charms':'Über Velvet Charms','Our studio is shaped by fourteen individual perspectives and a shared commitment to thoughtful, high-quality work.':'Unser Atelier wird von vierzehn unterschiedlichen Perspektiven und einem gemeinsamen Anspruch an sorgfältige, hochwertige Arbeit geprägt.','Made by hand, made to matter':'Von Hand gefertigt, mit Bedeutung','Every piece begins with materials, skill and a story. We work across painting, sculpture, resin, leather, textiles and mixed media to create objects that feel personal rather than mass-produced.':'Jedes Stück beginnt mit Material, handwerklichem Können und einer Geschichte. Wir arbeiten mit Malerei, Skulptur, Resin, Leder, Textilien und Mixed Media, um persönliche Objekte statt Massenware zu schaffen.','Created around your story':'Für Ihre Geschichte geschaffen','Many creations can be shaped around a photograph, a memory, a person, a pet, a place or an idea. We guide the details before production begins so the finished piece feels genuinely yours.':'Viele Kreationen können aus einem Foto, einer Erinnerung, einer Person, einem Tier, einem Ort oder einer Idee entstehen. Vor Produktionsbeginn stimmen wir die Details mit Ihnen ab, damit sich das fertige Stück wirklich persönlich anfühlt.','Beyond the catalogue':'Über den Katalog hinaus','Have Something Different in Mind?':'Sie haben etwas anderes im Sinn?','If the creation you are looking for is not currently displayed, send us your idea. When it fits the skills of our collective, we assess the materials, complexity, price and production timeframe individually before any work begins.':'Wenn die gewünschte Kreation derzeit nicht gezeigt wird, senden Sie uns Ihre Idee. Passt sie zu den Fähigkeiten unseres Kollektivs, bewerten wir Material, Aufwand, Preis und Fertigungszeit individuell, bevor die Arbeit beginnt.','Share your idea':'Idee teilen'
    }
  };
  const originals = new WeakMap();
  const norm = v => String(v || '').replace(/\s+/g,' ').trim();
  const getLang = () => (window.VELVET_GET_LANGUAGE?.() || document.documentElement.lang || 'en').slice(0,2).toLowerCase();
  function node(n){
    if (!originals.has(n)) originals.set(n,n.nodeValue);
    const original=originals.get(n), clean=norm(original), current=getLang();
    if (!clean) return;
    if (current==='en'){ n.nodeValue=original; return; }
    if (current==='ro') return;
    const value=maps[current]?.[clean]; if(!value) return;
    n.nodeValue=(original.match(/^\s*/)?.[0]||'')+value+(original.match(/\s*$/)?.[0]||'');
  }
  function tree(root=document.body){
    if(!root) return; if(root.nodeType===Node.TEXT_NODE) return node(root);
    if(!(root instanceof Element)||['SCRIPT','STYLE','NOSCRIPT'].includes(root.tagName)) return;
    const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let n;
    while((n=w.nextNode())) if(!['SCRIPT','STYLE','NOSCRIPT'].includes(n.parentElement?.tagName)) node(n);
  }
  let observer;
  function apply(){ observer?.disconnect(); tree(); observer?.observe(document.body,{childList:true,subtree:true}); }
  document.addEventListener('DOMContentLoaded',()=>{observer=new MutationObserver(ms=>{observer.disconnect();ms.forEach(m=>m.addedNodes.forEach(tree));observer.observe(document.body,{childList:true,subtree:true});});apply();});
  window.addEventListener('velvet-language-changed',apply); document.addEventListener('velvet:language-change',apply);
})();